version: "3.9"

services:
  node:
    container_name: node
    build: ./
    ports:
      - 80:3000
    volumes:
      - ./storage/posts:/app/public/posts
      - ./storage/database:/app/database
    env_file:
      - .env
