version: "3.8"

services:

  pinko_app:
    build:
      context: ./
    container_name: pinko_app
    restart: always
    ports:
      - 4000:4000
    environment:
      DATABASE_URL: ecto://${POSTGRESQL_USER}:${POSTGRESQL_PASSWORD}@pinko_postgres/pinko
    volumes:
      - ${UPLOADS_PATH}:/app/uploads
    networks:
      - pinko

  postgres:
    image: postgres:alpine
    container_name: pinko_postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    healthcheck:
      test: ["CMD", "echo", "'SELECT 1'", "|", "psql", "--host=127.0.0.1", "--username=${POSTGRESQL_USER}", "-w", "--dbname=pinko", "--quiet", "--no-align", "--tuples-only"]
      interval: 30s
      timeout: 10s
      start_period: 15s
    volumes:
      - postgres_datastore:/var/lib/postgresql/data
    networks:
      - pinko

networks:
  pinko:
    name: pinko
    driver: bridge

volumes:
  postgres_datastore: