version: "3.7"

services:

  nginx:
    # command: [nginx-debug, '-g', 'daemon off;']
    volumes:
      - ./nginx/conf/pinko.conf:/etc/nginx/conf.d/pinko.conf:ro
      - app:/app/src:ro

  php:
    volumes:
      - app:/app/src

  mysql:
    volumes:
      - mysql-datastore:/var/lib/mysql

  node:
    volumes:
      - app:/app/src:delegated
      - /app/src/.git # Ignore

volumes:
  mysql-datastore:
  app:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/../src/
      o: bind

networks:
  pinko:
    driver: bridge
