version: "3.7"

services:

  nginx:
    container_name: pinko_nginx
    build:
      context: ../
      dockerfile: ./Docker/nginx/Dockerfile
    restart: always
    volumes:
      - assets:/app/src/public/build
    ports:
      - ${HTTPS_PORT}:443
    networks:
      - pinko

  php:
    container_name: pinko_php
    build:
      context: ../
      dockerfile: ./Docker/php/Dockerfile
      target: ${ENV}
      args:
        - XDEBUG_ACTIVE=${XDEBUG_ACTIVE}
    restart: always
    entrypoint: /app/entrypoint.sh
    environment:
      APP_ENV: ${ENV}
      APP_DEBUG: ${SYMFONY_APP_DEBUG}
      DATABASE_URL: mysql://root:${MYSQL_PASS}@pinko_mysql:3306/pinko
      INSTAGRAM_CLIENT_ID: ${INSTAGRAM_CLIENT_ID}
      INSTAGRAM_CLIENT_SECRET: ${INSTAGRAM_CLIENT_SECRET}
      INSTAGRAM_REDIRECT_URI: ${INSTAGRAM_REDIRECT_URI}
      SILLY_PASSWORD_PROTECC: ${SILLY_PASSWORD_PROTECC}
    volumes:
      - storage:/app/src/public/uploads/posts
      - assets:/app/src/public/build
    networks:
      - pinko

  mysql:
    container_name: pinko_mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./mysql/datastore:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
    networks:
      - pinko

  node:
    container_name: pinko_node
    build:
      context: ../
      dockerfile: ./Docker/node/Dockerfile
      target: ${ENV}
    volumes:
      - assets:/app/src/public/build
    entrypoint: /app/entrypoint.sh
    environment:
      NODE_ENV: ${ENV}
    networks:
      - pinko

volumes:
  storage:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/../src/public/uploads/posts
      o: bind
  assets:

networks:
  pinko:
    driver: bridge
