index:
    path: /
    controller: App\Controller\DefaultController::index

about:
    path: /about
    controller: App\Controller\DefaultController::about

manifesto:
    path: /manifesto
    controller: App\Controller\DefaultController::manifesto

instagram_list:
    path: /api/instagram/list
    controller: App\Controller\API\InstagramController::list
    methods: GET