<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT7ZMt6l\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT7ZMt6l/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerT7ZMt6l.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerT7ZMt6l\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerT7ZMt6l\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'T7ZMt6l',
    'container.build_id' => '9deb3313',
    'container.build_time' => 1524309324,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerT7ZMt6l');
